org: jeilani
app: evergreen
service: evergreen-energy
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: 
          path: /api/v1/energy
          method: get
          cors: true



plugins:
  - serverless-offline
  - serverless-dotenv-plugin
